### ISSUE TITLE
sklearn_tuner.py example failing with pymoo version 0.5.0

### ISSUE THREAD

**Issue by Ryan-Rhys** [huawei-noah/HEBO#1]
Using the latest version of `pymoo==0.5.0` the `sklearn_tuner.py` example fails with the error:

`ModuleNotFoundError: No module named 'pymoo.algorithms.so_genetic_algorithm'`

It would be great if we could either make the example compatible with pymoo==0.5.0 or update the requirements and install instructions to specify pymoo==0.4.2 as the required version.

The example runs with pymoo==0.4.2 albeit breaks with a different error after 5 iterations:

```
/Users/~/opt/miniconda3/envs/hebo/bin/python /Users/ryan_rhys/ml_physics/HEBO/HEBO/hebo/sklearn_tuner.py
Iter 0, best metric: 0.389011
Iter 1, best metric: 0.496764
Iter 2, best metric: 0.649803
Iter 3, best metric: 0.649803
Iter 4, best metric: 0.649803
Iter 5, best metric: 0.649803
Traceback (most recent call last):
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/hebo/acq_optimizers/evolution_optimizer.py", line 119, in optimize
    res   = minimize(prob, algo, ('n_gen', self.iter), verbose = self.verbose)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/optimize.py", line 85, in minimize
    res = algorithm.solve()
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 226, in solve
    self._solve(self.problem)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 321, in _solve
    self.next()
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 246, in next
    self._next()
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/algorithms/genetic_algorithm.py", line 93, in _next
    self.off = self.mating.do(self.problem, self.pop, self.n_offsprings, algorithm=self)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/infill.py", line 40, in do
    _off = self.eliminate_duplicates.do(_off, pop, off)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/duplicate.py", line 26, in do
    pop = pop[~self._do(pop, None, np.full(len(pop), False))]
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/duplicate.py", line 75, in _do
    D = self.calc_dist(pop, other)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/model/duplicate.py", line 66, in calc_dist
    D = cdist(X, X)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/pymoo/util/misc.py", line 90, in cdist
    return scipy.spatial.distance.cdist(A, B, **kwargs)
  File "/Users/~/opt/miniconda3/envs/hebo/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2954, in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
ValueError: Unsupported dtype object
```

**Comment by Alaya-in-Matrix** [comment]
The issue has been fixed
